print('This program calculates and displays travel expenses')
print('Date: 10/03/2023')
print('CTI-110 P1HW2 - Travel Expense')
print('Stephen Hughes')
print()
budget = int(input('Enter Budget: '))
travel = (input('Enter Travel Destination: '))
gas = int(input('Enter Amount For Gas: '))
accommodation = int(input('Enter Amount For Accommodation: '))
food = int(input('Enter Amount For Food: '))

print('------------Travel Expenses------------')
print('Location:', travel)
print('Initial Buget:', budget)
print()

print('Fuel:', gas)
print('Accommodation:', accommodation)
print('Food:', food)
print()
print('Total:',  gas + accommodation + food )
print()
print('Remaining Balance:', budget - gas - accommodation - food )
