""" Program a budget for a trip """
print()
print('Date: 10/18/2023')
print('CTI-110 P2HW1  - Travel')
print('Stephen Hughes')
print()
print('This program calculates and displays travel expenses')
print()
budget = float(input('Enter Budget: '))
print()
travel = (input('Enter your travel destination: '))
print()
gas = float(input('How much do you think you will spend on gas? '))
print()
accommodation = float(input('Approximately, how much will you need for accommodation/hotel? '))
print()
food = float(input('Last, how much do you need for food? '))
print()
print('------------Travel Expenses------------')
print('Location:          ',travel)
print('Initial Buget:     ',budget)
print('Fuel:              ',gas)
print('Accommodation:     ',accommodation)
print('Food:              ',food)
print('---------------------------------------')
print()
print ("${0:<17}".format("Remaining Balance:", budget - gas - accommodation - food))
# print('Remaining Balance:', budget - gas - accommodation - food)

